SCALE_5_FREQ = ["1 - Niciodată", "2 - Rar", "3 - Uneori", "4 - Des", "5 - Întotdeauna"]
SCALE_4_BIS  = ["1 - Rar/niciodată", "2 - Ocazional", "3 - Deseori", "4 - Întotdeauna"]
SCALE_5_TRUE = ["1 - Deloc adevărat", "2 - Puțin adevărat", "3 - Moderat adevărat", "4 - Aproape complet adevărat", "5 - Complet adevărat"]
SCALE_5_FREQ2 = ["1 - Niciodată", "2 - Rareori", "3 - Uneori", "4 - Deseori", "5 - Aproape tot timpul"]
SCALE_5_AGREE = ["1 - Complet neadevărat", "2 - Mai degrabă neadevărat", "3 - Nici/nici", "4 - Mai degrabă adevărat", "5 - Complet adevărat"]
SCALE_5_POST  = ["1 - Complet în dezacord", "2 - În dezacord", "3 - Neutru", "4 - De acord", "5 - Complet de acord"]

PRE_SECTIONS = [
    {
        "title": "🧠 I. Funcționalitate dopaminergică",
        "instruction": "Indică cât de des se potrivește cu felul tău de a fi, în general.",
        "scale": SCALE_5_FREQ,
        "key_prefix": "dopa",
        "questions": [
            "Mă simt plin(ă) de energie când încep un proiect sau o provocare nouă.",
            "Caut varietate în viața mea de zi cu zi (locuri noi, experiențe, mâncare etc.).",
            "Îmi stabilesc des obiective personale și îmi place să lucrez pentru a le atinge.",
            "Mă plictisesc repede de sarcini repetitive.",
            "Simt o plăcere intensă când reușesc ceva important pentru mine.",
            "Sunt foarte motivat(ă) când există o posibilă recompensă.",
            "Acționez rapid atunci când observ o oportunitate.",
        ],
    },
    {
        "title": "🌤️ II. Funcționalitate serotoninergică",
        "instruction": "Indică cât de des se potrivește cu felul tău de a fi, în general.",
        "scale": SCALE_5_FREQ,
        "key_prefix": "sero",
        "questions": [
            "De obicei rămân calm(ă) chiar și în situații dificile.",
            "Am rareori schimbări bruște de dispoziție.",
            "Tind să mă îngrijorez excesiv.",
            "Îmi este ușor să amân gratificarea.",
            "Reflectez adesea înainte să reacționez emoțional.",
            "Mă simt stabil(ă) din punct de vedere emoțional în majoritatea zilelor.",
            "Rareori mă simt copleșit(ă) de stres.",
        ],
    },
    {
        "title": "💞 III. Funcționalitate oxitocinergică",
        "instruction": "Indică cât de des se potrivește cu felul tău de a fi, în general.",
        "scale": SCALE_5_FREQ,
        "key_prefix": "oxyt",
        "questions": [
            "Mă simt conectat(ă) emoțional cu persoanele apropiate.",
            "Îmi vine ușor să am încredere în alții, chiar și când îi întâlnesc prima dată.",
            "Îmi place apropierea fizică (îmbrățișări, atingere) cu cei dragi.",
            "Intuiesc adesea ce simt alții, fără să-mi spună.",
            "Simt o satisfacție puternică atunci când ajut pe cineva.",
            "Îmi place să formez relații profunde și de lungă durată.",
            "Mă emoționează interacțiunile sociale pozitive.",
        ],
    },
    {
        "title": "💪 IV. Funcționalitate endorfinergică",
        "instruction": "Indică cât de des se potrivește cu felul tău de a fi, în general.",
        "scale": SCALE_5_FREQ,
        "key_prefix": "endo",
        "questions": [
            "Mă simt mai bine după activitate fizică sau exercițiu.",
            "Tolerez mai ușor disconfortul fizic decât majoritatea oamenilor.",
            "Râd des cu prieteni sau familie.",
            "Simt un impuls puternic al dispoziției după ce ascult muzica preferată.",
            "Folosesc umorul pentru a gestiona situații dificile.",
            "Mă simt liniștit(ă) după ce petrec timp în natură.",
            "Rareori simt tensiune fizică în perioade stresante.",
        ],
    },
    {
        "title": "🧠 Scala BIS-11",
        "instruction": "Alege cât de mult se aplică în cazul tău, în general.",
        "scale": SCALE_4_BIS,
        "key_prefix": "bis",
        "questions": [
            "Îmi vine greu să mă concentrez pe o singură activitate.",
            "Trec repede de la un gând la altul fără legătură.",
            "Vorbesc fără să mă gândesc bine înainte.",
            "Îmi pierd rapid interesul pentru ce fac.",
            "Îmi este greu să finalizez lucruri începute.",
            "Acționez din instinct, fără să analizez situația.",
            "Îmi schimb planurile fără motiv clar.",
            "Mă întrerup ușor în timp ce lucrez sau studiez.",
            "Am tendința să întrerup oamenii în conversații.",
            "Acționez rapid, fără să stau pe gânduri.",
            "Am dificultăți în a rămâne calm(ă) când trebuie să aștept.",
            "Nu suport sarcinile care cer răbdare sau rutină.",
            "Mă implic în activități riscante fără a evalua toate datele.",
            "Am momente în care fac lucruri fără să-mi dau seama de ce.",
            "Fac uneori cumpărături scumpe sau impulsive fără plan.",
            "Mă enervez ușor și reacționez pe moment.",
            "Nu obișnuiesc să planific pe termen lung.",
            "Tind să trăiesc «clipa» fără să mă gândesc la viitor.",
            "Nu-mi organizez cheltuielile decât când e prea târziu.",
            "Gândesc adesea «las că văd eu ce fac când ajung acolo».",
            "Mă bazez mai mult pe impuls decât pe strategie.",
            "Mă trezesc că iau decizii importante fără analiză.",
            "Încep proiecte fără să estimez cât timp sau resurse necesită.",
            "Nu mă gândesc la consecințe decât după ce acționez.",
            "Mă simt obligat(ă) să acționez imediat când sunt furios/oasă.",
            "Când sunt stresat(ă), iau decizii rapide și regret apoi.",
            "Emoțiile intense mă fac să pierd controlul acțiunilor.",
            "Când sunt foarte entuziasmat(ă), nu mă mai gândesc la riscuri.",
            "Mă calmez greu după ce iau o decizie impulsivă greșită.",
            "Îmi pare rău adesea pentru lucruri făcute «la nervi» sau «la impuls».",
        ],
    },
    {
        "title": "🔹 Satisfacție generală cu viața",
        "instruction": "Răspunde sincer, în funcție de cum te simți în general.",
        "scale": SCALE_5_TRUE,
        "key_prefix": "swl",
        "questions": [
            "În general, sunt mulțumit(ă) de viața mea.",
            "Simt că am obținut ceea ce mi-am dorit în viață până acum.",
            "Viața mea se apropie, în mare parte, de idealul meu personal.",
            "Dacă ar trebui să trăiesc din nou, nu aș schimba aproape nimic.",
            "Am mai multe lucruri în viața mea de care pot fi recunoscător/oare.",
        ],
    },
    {
        "title": "🔹 Afect pozitiv și energie vitală",
        "instruction": "Răspunde sincer, în funcție de cum te simți în general.",
        "scale": SCALE_5_TRUE,
        "key_prefix": "who5",
        "questions": [
            "M-am simțit energic(ă) și plin(ă) de viață în ultimele zile.",
            "Am avut momente în care m-am bucurat sincer de lucruri simple.",
            "Am avut o dispoziție senină și echilibrată.",
            "M-am simțit motivat(ă) să încep sau să finalizez lucruri.",
            "Am simțit apropiere sau conexiune pozitivă cu alți oameni.",
            "Am râs sau am zâmbit sincer frecvent în ultimele zile.",
            "M-am simțit competent(ă) și capabil(ă) în ce am făcut.",
        ],
    },
    {
        "title": "🔹 Afect negativ și distres",
        "instruction": "Răspunde sincer, în funcție de cum te simți în general.",
        "scale": SCALE_5_TRUE,
        "key_prefix": "neg_aff",
        "questions": [
            "M-am simțit copleșit(ă) de grijile personale sau financiare.",
            "M-am simțit fără speranță sau lipsit(ă) de motivație.",
            "Am fost iritabil(ă) sau frustrat(ă) fără un motiv clar.",
            "M-am simțit singur(ă) sau deconectat(ă) de ceilalți.",
            "M-am simțit neîncrezător/neîncrezătoare în forțele proprii.",
            "Am avut dificultăți în a dormi sau a mă relaxa.",
            "Am simțit o stare de tensiune interioară constantă.",
        ],
    },
    {
        "title": "🔹 Eudaimonie și sens în viață",
        "instruction": "Răspunde sincer, în funcție de cum te simți în general.",
        "scale": SCALE_5_TRUE,
        "key_prefix": "euda",
        "questions": [
            "Simt că ceea ce fac are sens și valoare pentru mine.",
            "Trăiesc în acord cu valorile mele personale.",
            "Simt că viața mea are o direcție clară.",
            "Simt că evoluez ca persoană și învăț lucruri relevante.",
            "Mă simt implicat(ă) în activități care îmi dau un sentiment de împlinire.",
            "Simt că am un scop personal care mă ghidează.",
        ],
    },
    {
        "title": "🔹 Resurse psihologice și reziliență",
        "instruction": "Răspunde sincer, în funcție de cum te simți în general.",
        "scale": SCALE_5_TRUE,
        "key_prefix": "resil",
        "questions": [
            "Simt că pot face față eficient situațiilor dificile.",
            "Când trec prin momente grele, găsesc modalități de a merge mai departe.",
            "Sunt capabil(ă) să-mi reglez emoțiile când e nevoie.",
            "Mă adaptez relativ repede la schimbări neprevăzute.",
            "Am o imagine de sine sănătoasă, chiar și când lucrurile merg prost.",
        ],
    },
    {
        "title": "🔹 Stres perceput",
        "instruction": "Cum te-ai simțit în ultimele 7 zile?",
        "scale": SCALE_5_FREQ2,
        "key_prefix": "pss",
        "questions": [
            "Cât de des te-ai simțit copleșit(ă) de sarcinile zilnice?",
            "Cât de des ți s-a părut că nu poți controla lucruri importante din viața ta?",
            "Cât de des te-ai simțit nervos/oasă sau încordat(ă) fără un motiv clar?",
            "Cât de des ai simțit că ești depășit(ă) de evenimente sau responsabilități?",
            "Cât de des ai simțit că nu ai suficient timp pentru tine?",
            "Cât de des ai avut impresia că ceilalți așteaptă prea mult de la tine?",
            "Cât de des ai simțit că ești aproape de epuizare fizică sau psihică?",
        ],
    },
    {
        "title": "🔹 Stare emoțională – Afect negativ",
        "instruction": "Cum te-ai simțit în ultimele 7 zile?",
        "scale": SCALE_5_FREQ2,
        "key_prefix": "mood_neg",
        "questions": [
            "M-am simțit tensionat(ă) sau iritabil(ă).",
            "M-am simțit anxios/anxioasă sau cu inima strânsă.",
            "Am simțit tristețe sau lipsă de speranță.",
            "M-am simțit vinovat(ă) sau auto-critic(ă).",
            "M-am simțit neliniștit(ă), ca și cum «nu pot sta locului».",
            "M-am simțit singur(ă) sau deconectat(ă) de ceilalți.",
        ],
    },
    {
        "title": "🔹 Stare emoțională – Afect pozitiv",
        "instruction": "Cum te-ai simțit în ultimele 7 zile?",
        "scale": SCALE_5_FREQ2,
        "key_prefix": "mood_pos",
        "questions": [
            "M-am simțit energic(ă) și activ(ă).",
            "M-am simțit calm(ă) și echilibrat(ă) emoțional.",
            "M-am simțit mulțumit(ă) cu mine și cu viața mea.",
            "M-am simțit în controlul situației.",
            "M-am simțit motivat(ă) să acționez și să finalizez sarcini.",
            "Am avut momente în care m-am bucurat sincer de ceea ce făceam.",
        ],
    },
    {
        "title": "🔹 Reacții fiziologice și comportamentale",
        "instruction": "Cum te-ai simțit în ultimele 7 zile?",
        "scale": SCALE_5_FREQ2,
        "key_prefix": "physio",
        "questions": [
            "Am avut probleme cu somnul (dificultăți de adormire, treziri frecvente etc.).",
            "Mi-am pierdut pofta de mâncare sau am mâncat compulsiv.",
            "Am evitat interacțiuni sociale sau am preferat izolarea.",
            "Mi-a fost greu să mă concentrez sau să finalizez lucruri.",
            "Am avut stări de oboseală accentuată, chiar și fără efort fizic.",
            "Am resimțit dureri de cap, tensiune musculară sau disconfort fizic fără cauze clare.",
        ],
    },
    {
        "title": "🔹 Reevaluare cognitivă",
        "instruction": "Cât de mult te regăsești în fiecare afirmație?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "reapp",
        "questions": [
            "Încerc să privesc situațiile stresante dintr-o altă perspectivă.",
            "Mă concentrez pe aspectele pozitive ale unei situații dificile.",
            "Reinterpretez ceea ce simt pentru a-mi păstra calmul.",
            "Îmi spun că lucrurile ar putea fi mai rele și asta mă liniștește.",
            "Îmi ajustez gândurile pentru a reduce impactul emoțional.",
        ],
    },
    {
        "title": "🔹 Suprimarea expresiei emoționale",
        "instruction": "Cât de mult te regăsești în fiecare afirmație?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "suppr",
        "questions": [
            "Evit să arăt când sunt trist(ă) sau afectat(ă).",
            "Îmi ascund emoțiile în fața celorlalți.",
            "Încerc să nu exprim ce simt, chiar dacă e intens.",
            "Mă abțin să arăt furia sau frustrarea în public.",
            "Nu las emoțiile să mi se citească pe față.",
        ],
    },
    {
        "title": "🔹 Impulsivitate emoțională",
        "instruction": "Cât de mult te regăsești în fiecare afirmație?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "emo_imp",
        "questions": [
            "Când simt ceva puternic, acționez imediat.",
            "Reacționez fără să mă gândesc, atunci când sunt supărat(ă).",
            "Când sunt furios/oasă, îmi pierd controlul.",
            "Nu pot să-mi stăpânesc acțiunile când sunt copleșit(ă) emoțional.",
            "Spun sau fac lucruri regretabile când sunt tensionat(ă).",
        ],
    },
    {
        "title": "🔹 Conștientizarea și înțelegerea emoțiilor",
        "instruction": "Cât de mult te regăsești în fiecare afirmație?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "emo_aware",
        "questions": [
            "Pot să-mi identific emoțiile ușor.",
            "Știu ce simt, chiar și când e complicat.",
            "Observ rapid când starea mea emoțională se schimbă.",
            "Îmi înțeleg reacțiile afective fără efort.",
            "Mă pot exprima clar despre ceea ce simt.",
        ],
    },
    {
        "title": "🔹 Acceptarea emoțiilor",
        "instruction": "Cât de mult te regăsești în fiecare afirmație?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "emo_acc",
        "questions": [
            "Încerc să ignor emoțiile negative.",
            "Mă simt inconfortabil când sunt copleșit(ă) emoțional.",
            "Nu îmi permit să simt furie sau frică.",
            "Evit emoțiile dureroase cât de mult pot.",
            "Nu suport să simt vulnerabilitate.",
            "Emoțiile intense mă fac să mă retrag.",
        ],
    },
    {
        "title": "🔹 Claritate emoțională și reglaj adaptiv",
        "instruction": "Cât de mult te regăsești în fiecare afirmație?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "emo_reg",
        "questions": [
            "Mă pot liniști singur(ă) în momente dificile.",
            "Am metode clare prin care îmi reglez emoțiile.",
            "Pot face față unui conflict fără să explodez.",
            "Îmi revin relativ repede după un moment de criză.",
            "Pot cere ajutor emoțional când am nevoie.",
            "Îmi folosesc rațiunea chiar și când emoțiile sunt intense.",
            "Simt că am control asupra reacțiilor mele afective.",
            "Pot comunica emoțiile într-un mod care nu rănește.",
            "Mă ajut de activități (sport, scris, meditație) ca să mă reglez.",
            "Când ceva mă copleșește, știu exact ce strategie emoțională să aplic.",
        ],
    },
    {
        "title": "🔹 Big Five – Deschidere către experiență",
        "instruction": "Cât de bine te descriu afirmațiile de mai jos?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "open",
        "questions": [
            "Îmi place să explorez idei noi și concepte abstracte.",
            "Mă bucur de artă, muzică și forme creative de exprimare.",
            "Sunt curios/oasă intelectual și deschis(ă) la perspective alternative.",
            "Mă plictisesc repede în contexte monotone sau rigide.",
        ],
    },
    {
        "title": "🔹 Big Five – Conștiinciozitate",
        "instruction": "Cât de bine te descriu afirmațiile de mai jos?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "cons",
        "questions": [
            "Îmi organizez timpul și sarcinile cu grijă.",
            "Mă țin de angajamente chiar și când devine dificil.",
            "Îmi place să finalizez ce încep.",
            "Sunt atent(ă) la detalii și evit greșelile prin planificare.",
        ],
    },
    {
        "title": "🔹 Big Five – Extraversiune",
        "instruction": "Cât de bine te descriu afirmațiile de mai jos?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "extra",
        "questions": [
            "Mă simt energizat(ă) în prezența altor persoane.",
            "Îmi place să fiu în centrul atenției.",
            "Mă exprim ușor în grupuri și conversații sociale.",
            "Prefer activitățile dinamice, cu interacțiune.",
        ],
    },
    {
        "title": "🔹 Big Five – Agreabilitate",
        "instruction": "Cât de bine te descriu afirmațiile de mai jos?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "agree",
        "questions": [
            "Încerc să evit conflictele și să mențin armonia.",
            "Mă consider empatic(ă) și atent(ă) la nevoile altora.",
            "Sunt dispus(ă) să ajut, chiar dacă nu mi se cere.",
            "Îmi pasă sincer de bunăstarea celor din jur.",
        ],
    },
    {
        "title": "🔹 Big Five – Nevrotism",
        "instruction": "Cât de bine te descriu afirmațiile de mai jos?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "neuro",
        "questions": [
            "Mă simt frecvent neliniștit(ă) sau îngrijorat(ă).",
            "Reacționez puternic la stres.",
            "Am tendința de a analiza în exces greșelile mele.",
            "Mă simt ușor copleșit(ă) în fața incertitudinii.",
        ],
    },
    {
        "title": "🔹 Trăsături interpersonale",
        "instruction": "Cât de bine te descriu afirmațiile de mai jos?",
        "scale": SCALE_5_AGREE,
        "key_prefix": "dark",
        "questions": [
            "Cred că e mai important să fii eficient decât moral.",
            "Oamenii se lasă manipulați ușor dacă le cunoști slăbiciunile.",
            "Îmi place să influențez deciziile altora subtil, în favoarea mea.",
            "În relațiile sociale, controlez informațiile pe care le ofer.",
            "Merit să fiu admirat(ă) pentru cine sunt.",
            "Sunt o persoană specială, diferită de ceilalți.",
            "Îmi place să mi se recunoască valoarea, chiar dacă trebuie să insist.",
            "Cred că am calități care mă fac superior/oară majorității.",
            "Nu simt vină pentru lucruri făcute sub impuls.",
            "Îmi este greu să simt remușcări chiar dacă știu că am greșit.",
            "Trec rapid peste suferința altora – viața merge înainte.",
            "Îmi plac riscurile și trăirile intense, chiar dacă implică reguli încălcate.",
        ],
    },
]

POST_SECTIONS = [
    {
        "title": "Stare psihologică după scenariu",
        "instruction": "Indicați cât de mult sunteți de acord cu fiecare afirmație, în funcție de cum vă simțiți acum.",
        "scale": SCALE_5_POST,
        "key_prefix": "post",
        "questions": [
            "Mă simt energizat(ă) și plin(ă) de entuziasm în acest moment.",
            "Sunt foarte motivat(ă) să încep o activitate nouă acum.",
            "Gândul de a mă apuca de următoarea sarcină mi se pare atrăgător și stimulativ.",
            "Mă simt liniștit(ă) și relaxat(ă), fără tensiune.",
            "Mă simt mulțumit(ă) și în armonie cu mine.",
            "Mă simt într-o dispoziție general pozitivă.",
            "Simt o conexiune socială cu ceilalți participanți.",
            "Simt că pot avea încredere în oamenii din jur în acest moment.",
            "Simt căldură emoțională și apropiere față de cei din jur.",
        ],
    },
]
